[package]
name = "encointer-node-runtime"
version = "4.0.1"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"



[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.safe-mix]
default-features = false
version = "1.0"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
features = ["derive"]
version = "1.0.0"

[dependencies.rstd]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-std"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.runtime-io]
default-features = false
path = '../sr-tee-io'
package = 'sr-io'

[dependencies.version]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-version"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.support]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-support"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.substrate-session]
default-features = false
git = "https://github.com/paritytech/substrate"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.balances]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-balances"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.babe]
default-features = false
#optional = true
git = "https://github.com/paritytech/substrate"
package = "srml-babe"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.babe-primitives]
default-features = false
#optional = true
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-babe-primitives"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.executive]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-executive"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.indices]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-indices"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.grandpa]
default-features = false
#optional = true
git = "https://github.com/paritytech/substrate"
package = "srml-grandpa"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.system]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-system"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.timestamp]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-timestamp"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.sudo]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "srml-sudo"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.runtime-primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "sr-primitives"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.client]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-client"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[dependencies.offchain-primitives]
default-features = false
git = "https://github.com/paritytech/substrate"
package = "substrate-offchain-primitives"
rev = "9b08e7ff938a45dbec7fcdb854063202e2b0cb48"

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.3" }

[features]
default = ["std", "enable_host_calls"]
std = [
    "codec/std",
    "client/std",
    "rstd/std",
    "runtime-io/std",
    "support/std",
    "balances/std",
    "babe/std",
    "babe-primitives/std",
    "executive/std",
    "indices/std",
    "grandpa/std",    
    "primitives/std",
    "runtime-primitives/std",
    "system/std",
    "timestamp/std",
    "sudo/std",
    "version/std",
    "serde",
    "safe-mix/std",
    "offchain-primitives/std",
    "substrate-session/std",   
]
no_global_allocator = [
	"rstd/no_global_allocator",
]
no_panic_handler = [
    "runtime-io/no_panic_handler"
]
no_oom = [
    "runtime-io/no_oom"
]

enable_host_calls = [
    "runtime-io/enable_host_calls",
]

no_std = [
]

[patch."https://github.com/paritytech/substrate"]
sr-io = { package = "sr-io", path = "../sr-tee-io", default-features = false}
substrate-executor = { path = "../substratee-executor", default-features = false}